/* Feito por
Gabriela Morais Gandine 
Lara Ono Glufke Reis

*/
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;

public class Calculadora extends javax.swing.JFrame implements ActionListener {

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() instanceof Numero){
            Numero.clicaNumero(e);
        } else if(e.getSource() instanceof Operador){
            Operador.clicaOperador(e);
        }
        System.out.print(status);
    }
    public enum Estados {
       INICIO,
       NUM1,
       OPERADOR,
       NUM2,
       RESULTADO,
       IGNORADO
   } 
    static private Calculadora.Estados status = Calculadora.Estados.INICIO;
    static String[] vec = {"","",""};
    static int total = 0;
    static JTextArea resultado;

    public static Estados getStatus() {
        return status;
    }

    public static void setStatus(Estados status) {
        Calculadora.status = status;
    }

    public Calculadora() {
        resultado = new JTextArea();
        JPanel res = new JPanel();
        JPanel botoes = new JPanel();
        JButton[] botao = new JButton[16];

        res.add(resultado);
        res.setLayout(new GridLayout(1, 1));
        
        for (int i = 1; i <= 16; i++) {
            if (i % 4 == 0 || i == 13 || i == 15) {
                botao[i - 1] = new Operador();
            } else {
                botao[i - 1] = new Numero();
            }
            botao[i - 1].addActionListener(this);
            botoes.add(botao[i - 1]);
        }
        botoes.setLayout(new GridLayout(4, 4, 2, 2));

        this.setLayout(new BorderLayout());
        this.add(res, BorderLayout.NORTH);
        this.add(botoes, BorderLayout.CENTER);
        this.pack();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }
    static void calcularResultado() {
        int n1;
        n1 = Integer.parseInt(vec[0]);
        int n2;
        n2 = Integer.parseInt(vec[1]);
        try{
            switch(vec[2]){
                case "+" -> total = n1+n2;
                case "-" -> total = n1-n2;
                case "*" -> total = n1*n2;
                case "/" -> total = n1/n2;

            } 
      
            Calculadora.resultado.setText(String.valueOf(total));
            setVetor(String.valueOf(total),"","",Calculadora.Estados.RESULTADO);
        }
        catch(Exception e){
            Calculadora.resultado.setText("ERROR!");
            setVetor("","","",Calculadora.Estados.RESULTADO);
         }
    }
    
    static void setVetor(String vet1,String vet2,String vet3,Calculadora.Estados estado){
        Calculadora.vec[0] = vet1;
        Calculadora.vec[1] = vet2;
        Calculadora.vec[2] = vet3;
        Calculadora.status = estado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculadora().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
