package CampoMinado;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author isaon
 */
public class jogoFrame extends javax.swing.JFrame implements ActionListener, MouseListener {

    private int nivel = 1;
    private int flags = 0;
    private int numBombas;
    private Casas[][] btn;
    private int alt =0, larg = 0;
    private JPanel tabuleiro;
    private Boolean end = false;

    /**
     * Creates new form jogoFrame
     */
    public jogoFrame() {
        
        initComponents();
        criarCampo();

    }

    public void criarCampo(){
        this.tabuleiro = new JPanel();
        alt = 9;
        larg = 9;
        numBombas = 9;
        switch(this.nivel){
            case 2: alt = 16; larg = 16; numBombas = 16; break;
            case 3: alt = 16; larg = 30; numBombas = 30; break;
        }
        this.tabuleiro.setLayout(new GridLayout(alt,larg));
        
         btn = new JButton[alt][larg];
        for(int i = 0; i<alt;i++){
            for(int j = 0; j<larg;j++){
                btn[i][j] = new JButton();
                btn[i][j].addMouseListener(this);
                btn[i][j].setName("");
                this.tabuleiro.add(btn[i][j]);
        }
        }
        this.setArrayBombas();
        this.setArrayVizinhos();
         this.campo.add(tabuleiro);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        pontos = new javax.swing.JTextField();
        tempo = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        campo = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jogo = new javax.swing.JMenu();
        facil = new javax.swing.JMenuItem();
        medio = new javax.swing.JMenuItem();
        dificil = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenu();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pontos.setText("PONTOS");

        tempo.setText("TEMPO");
        tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempoActionPerformed(evt);
            }
        });

        reset.setText(":)");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset)
                .addGap(320, 320, 320)
                .addComponent(tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset)))
        );

        campo.setLayout(new java.awt.GridLayout(1, 0));

        jogo.setText("Jogo");
        jogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogoActionPerformed(evt);
            }
        });

        facil.setText("Fácil");
        facil.setActionCommand("facil");
        facil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facilActionPerformed(evt);
            }
        });
        jogo.add(facil);

        medio.setText("Médio");
        medio.setActionCommand("medio");
        medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medioActionPerformed(evt);
            }
        });
        jogo.add(medio);

        dificil.setText("Difícil");
        dificil.setActionCommand("dificil");
        dificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificilActionPerformed(evt);
            }
        });
        jogo.add(dificil);

        jMenuBar1.add(jogo);

        ajuda.setText("Ajuda");
        ajuda.setActionCommand("ajuda");
        ajuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajudaMouseClicked(evt);
            }
        });
        ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaActionPerformed(evt);
            }
        });
        jMenuBar1.add(ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

    }//GEN-LAST:event_resetActionPerformed

    private void tempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempoActionPerformed

    private void jogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogoActionPerformed
      actionPerformed(evt);
    }//GEN-LAST:event_jogoActionPerformed

    private void facilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilActionPerformed
     actionPerformed(evt);
    }//GEN-LAST:event_facilActionPerformed

    private void medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medioActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_medioActionPerformed

    private void dificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificilActionPerformed
        actionPerformed(evt);
    }//GEN-LAST:event_dificilActionPerformed

    private void ajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaActionPerformed
       System.out.print(evt.getActionCommand());
    }//GEN-LAST:event_ajudaActionPerformed

    private void ajudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajudaMouseClicked
       ajudaDisplay();
    }//GEN-LAST:event_ajudaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jogoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajuda;
    private javax.swing.JPanel campo;
    private javax.swing.JMenuItem dificil;
    private javax.swing.JMenuItem facil;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu jogo;
    private javax.swing.JMenuItem medio;
    private javax.swing.JTextField pontos;
    private javax.swing.JButton reset;
    private javax.swing.JTextField tempo;
    // End of variables declaration//GEN-END:variables

    private void ajudaDisplay(){
       ajudaDialog ajuda = new ajudaDialog(this,true);
       ajuda.setVisible(true);
    }
    
    private void setCampo(int lvl){
        if(this.nivel != lvl){
            this.nivel = lvl;
            this.campo.remove(this.tabuleiro);
            this.tabuleiro.removeAll();
            criarCampo();
            this.campo.add(this.tabuleiro);
            revalidate();
            repaint();
        }
        
        
    }
     
   
    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.print(e.getActionCommand());
        switch(e.getActionCommand()){
            case "facil" -> {System.out.print("FACIL");setCampo(1);break;}
            case "medio" -> {System.out.print("MEDIO");setCampo(2);break;}
            case "dificil" -> {System.out.print("DIFICIL");setCampo(3);break;}
        }
    }
    
    @Override
    public void mousePressed(MouseEvent e) {
          
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        
    }

    @Override
    public void mouseEntered(MouseEvent e) {
       
    }

    @Override
    public void mouseExited(MouseEvent e) {
        
    }

    @Override
    public void mouseClicked(MouseEvent e) {
         
         
         if(SwingUtilities.isRightMouseButton(e)){
            System.out.printf("Click");
            if(e.getComponent() instanceof JButton){
                JButton flag = (JButton) e.getComponent();
                
                if(flag.getText().equals("+") && this.flags > 0){
                flag.setText("");
                this.flags--;
                }else {
                if(this.flags < this.numBombas){
                flag.setText("+");
                this.flags++;
                }
                }
                
            }
        }
         if(SwingUtilities.isLeftMouseButton(e)){
             System.out.printf("Click");
            if(e.getComponent().getName().equals("*")){
                reset.setText(":(");
                end = true;
                for(int i = 0; i < alt; i++){
                    for(int j = 0; j < larg; j++){
                        if(btn[i][j].getName().equals("*")){
                            btn[i][j].setText("*");
                        }
                    }
                }
            }
            else{
                 JButton btn = (JButton) e.getComponent();
                if(!btn.getName().equals("")){
               btn.setText(btn.getName());
                }else {
                //recursao
                }
            }
         }
         
            }

    private void setArrayBombas() {
        Random gera = new Random();
       for(int i = 0; i < numBombas; i++){
           int m = gera.nextInt(alt);
           int n = gera.nextInt(larg);
           btn[m][n].setName("*");
       }
    }
    
    
    
    private void setArrayVizinhos(){
        for(int i = 0; i < alt; i++){
            for(int j = 0; j < larg; j++){
                if(btn[i][j].getName().equals("*")){
                    for(int m = -1; m <= 1; m++){
                        for(int n = -1; n <= 1; n++){
                          if (i + m >= 0 && i + m < alt && j + n >= 0 && j + n < larg) {
                            if(!btn[i+m][j+n].getName().equals("*")){
                              int valorVizinho = 1;
                              if(!btn[i+m][j+n].getName().equals("")){
                                valorVizinho = Integer.parseInt(btn[i+m][j+n].getName());
                                valorVizinho++;
                              }
                              btn[i+m][j+n].setName(Integer.toString(valorVizinho));
                            }
                          }
                        }
                      }

                }
            }
         }
    }
}
